#!/bin/bash
if printf "%s\n" $(echo "$WATER" | tr 'water' '01234') + $(echo "$STIR" | tr 'stir.' '01234') | grep -qE '^[0-9]+$'; then printf "%s\n" $(echo "$WATER" | tr 'water' '01234') + $(echo "$STIR" | tr 'stir.' '01234') | bc | tr '01234567' 'bestcholl'; fi
